server:
  port: 8080

management:
  endpoints:
    web:
      exposure.include: '*'
    shutdown.enabled: true

spring:
  datasource:
    url: jdbc:log4jdbc:h2:~/testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:
  h2.console: #http://localhost:8080/h2-console
    enabled: true
  sql.init:
    mode: always
    schema-locations:
      - classpath:/sql/ddl.sql
    data-locations:
      - classpath:/sql/dml.sql
  transaction:
    rollback-on-commit-failure: true
    default-timeout: 10s

mybatis:
  mapper-locations:
  - classpath*:/mybatis/*Mapper.xml
